# docker-compose
services:
  tengine:
    image: jas0n0ss/tengine:arm64
    container_name: tengine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status"]
      interval: 30s
      timeout: 5s
      retries: 3

